apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tapps.apps.tkestack.io
spec:
  group: apps.tkestack.io
  version: v1
  names:
    kind: TApp
    listKind: TAppList
    plural: tapps
    singular: tapp
  scope: Namespaced
  subresources:
    status: {}
    scale:
      labelSelectorPath: .status.scaleLabelSelector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
